export const month = [
    {   mon: 1,
        tue:  2,
        wed:  3,
        thur: 4,
        fri: 5,
        sat:  6,
        sun:  7,
    },
    {   mon: 8,
        tue:  9,
        wed:  10,
        thur: 11,
        fri: 12,
        sat:  13,
        sun:  14,
    },
    {   mon: 15,
        tue:  16,
        wed:  17,
        thur: 18,
        fri: 19,
        sat:  20,
        sun:  21,
    },
    {   mon: 22,
        tue:  23,
        wed:  24,
        thur: 25,
        fri: 26,
        sat:  27,
        sun:  28,
    },
    {   mon: 29,
        tue:  30,
        wed:  "",
        thur: "",
        fri:  "",
        sat:  "",
        sun:  "",
    },
]